### ISSUE TITLE
aligned org question

### ISSUE THREAD

**Issue by matosimi** [tebe6502/Mad-Assembler#1]
Hi TeBe,

is it possible to nicely perform aligned org?

Something like    .align $400  (to align charset data) , but instead of filling the space with zeros, I would like something like org * / $400*$400+$400   .

Is there any nicer way how to write this in MADS?

thanks

**Comment by tebe6502** [comment]
.align $400,fill_value

**Comment by matosimi** [comment]
> .align $400,fill_value
this is not exactly what i was looking for.

I do not want to fill the gap, but start new data block instead with new ORG that is aligned to $400.

**Comment by tebe6502** [comment]
mads.exe -fv:fill_value

**Comment by matosimi** [comment]
nevermind, i will go forward with my own macro... this is what i meant:

```
	org $1000
	dta 10,10
	orgalign $400
	dta 20,20
	orgalign $400
	dta 30,30
	orgalign $100
	dta 40,40
	
.macro	orgalign ' '
	org */:1*:1+:1
.endm
```


and checkxex output:

```
001:     $1000 $1001: $0002
002:     $1400 $1401: $0002
003:     $1800 $1801: $0002
004:     $1900 $1901: $0002
File 'orgalign.xex' is OK.

```
