### ISSUE TITLE
MWA produced optimized code with R- option

### ISSUE THREAD

**Issue by banxian** [tebe6502/Mad-Assembler#11]
```
	OPT h-
	OPT r-
	ORG $1D00

.proc	entry
	MWA #$ffff $80
.endp
```
this MWA macro expands to 
LDA #$FF 
STA $80
STA $81
it should be 
LDA #$FF 
STA $80
LDA #$FF 
STA $81
with r- optimization suppression.

**Comment by tebe6502** [comment]
is a feature of MWA (XASM-compatible), independent of the R option

**Comment by banxian** [comment]
thanks, got it. I can declare a new macro name which expands to two MVA.
