### ISSUE TITLE
inverse last byte in dta directive

### ISSUE THREAD

**Issue by ehn-pkalinowski** [tebe6502/Mad-Assembler#21]
Proposal - add another modifier, similar to `*` to `dta` directive.

`*` EORs with $80 the whole string.
`^` would EOR just the last byte.

This feature is available for ATASCII strings with `.cb` but not for INTERNAL codes.

**Comment by Pecusx** [comment]
Please add this! :)

**Comment by tebe6502** [comment]
this feature has been added
