### ISSUE TITLE
String allocations in struct instances do not allocate memory correctly

### ISSUE THREAD

**Issue by markjfisher** [tebe6502/Mad-Assembler#24]
As reported here https://forums.atariage.com/topic/352982-mads-struct-questions-how-to-get-size-and-fill-string-data/?do=findComment&comment=5283920

The following demonstrates that allocating strings over 1 char in size incorrectly allocates additional memory to the field:

```asm
    org $4000
.STRUCT tmp
     ssid  :3 .byte
     pass  :3 .byte
.ENDS

mydata DTA tmp[3] ('1','2') ('34','56') ('789','abc')
    lda mydata[0].ssid
    lda mydata[0].pass
    lda mydata[1].ssid
    lda mydata[1].pass
```

Looking at the assembled bytes after 6 byte header:

```
0000000 31 00 00 32 00 00 33 34 00 00 35 36 00 00 37 38
0000020 39 00 00 61 62 63 00 00 37 38 39 00 00 61 62 63
0000040 00 00 ad 00 40 ad 03 40 ad 06 40 ad 09 40
```

We can see that for "1" it puts in "31 00 00", fine.
We can see that for "2" it puts in "32 00 00", fine.

We can see that for "34" it puts in "33 34 00 00" - an extra 00 at the end
We can see that for "56" it puts in "35 36 00 00" - an extra 00 at the end

We can see that for "789" it puts in "37 38 39 00 00" - extra 00 00
We can see that for "abc" it puts in "61 62 63 00 00" - extra 00 00

All these extra zeroes are wrong.
It always puts in the number equal to the previous string's length - 1.

**Comment by tebe6502** [comment]
STRING in STRUCT is not allowed
