### ISSUE TITLE
Needs a license

### ISSUE THREAD

**Issue by davidgiven** [tebe6502/Mad-Assembler#28]
Hello ---

I'd like to use this to assemble a program for CP/M-65, but I'm trying to restrict myself to provably open source software to avoid issues down the line. MADS has no license attached (that I can find), which means that technically it can't be used or downloaded by anyone! There isn't even a copyright statement. As it's pretty clear that it's intended to be open source, can we have a license, please? I'm happy to assist with the license choice if necessary...

**Comment by tebe6502** [comment]
I forgot

https://github.com/tebe6502/Mad-Assembler/blob/master/LICENSE

**Comment by davidgiven** [comment]
That's brilliant --- thank you very much!
