### ISSUE TITLE
Add date of compile to the self-intro string, like it is in Mad-Pascal.

### ISSUE THREAD

**Issue by jhusak** [tebe6502/Mad-Assembler#33]
There are always some bugfixes and improvements, and the version gets not bumped often, maybe because changes are minor.
There is some confusion between the same versions and different behavior.

So I propose to add the date of compile to the presentation string.

**Comment by zbyti** [comment]
https://en.wikipedia.org/wiki/Software_versioning

**Comment by jhusak** [comment]
Tia?
