### ISSUE TITLE
mads.exe included twice

### ISSUE THREAD

**Issue by peterdell** [tebe6502/Mad-Assembler#35]
I like the idea of providing binary build for multiple OSes. But now we have a "mads.exe" in the main folder and an outdated "mads.exe" in the "bin/windows" folder. My proposal would be to remove the "mads.exe" in the root folder.

Also Windows has 32/64/ARM versions now, so naming the folder "windows_x86_64" would be logical.

Additional note on the macOS versions: Apples official naming now is "macos" instead of "macosx", because they are beyond "X" now

**Comment by tebe6502** [comment]
fixed
