### ISSUE TITLE
Possibility to separate high/low nibble in binary notation

### ISSUE THREAD

**Issue by mirao** [tebe6502/Mad-Assembler#4]
Just an idea:

This code
```asm
    lda CH
    ; Accept even upper case
    and #%10111111
```
would be more readable when separating nibbles by `_`:
```asm
    lda CH
    ; Accept even upper case
    and #%1011_1111
```

E.g. JavaScript allows similar thing: https://v8.dev/features/numeric-separators

**Comment by jhusak** [comment]
It is now done :)
Try please:
`   and #%1011 1111`

**Comment by mirao** [comment]
Well, it really works, thank you very much.

**Comment by mirao** [comment]
It doesn't work in the macro instruction `mva`, e.g. `mva #%1100 0000 GPRIOR`
Compiler fails on `ERROR: Extra characters on line`. It probably takes `0000` as a second argument.
