### ISSUE TITLE
Unable to have binary literal containing space in macro instruction "mva"

### ISSUE THREAD

**Issue by mirao** [tebe6502/Mad-Assembler#9]
**Steps:**

- Assemble a code with the instruction `mva #%1100 0000 GPRIOR` (MVA docs is [here](https://mads-atari8-info.translate.goog/pl/makro-rozkazy/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en-US#mva-mvx-mvy))

**Expected result:**

- Success. E.g. it works in `and #%1011 1111`, see #4.

**Actual result:**

- It fails: `ERROR: Extra characters on line`

Assembler seems to parse the `0000` as a second argument of `mva` instead of the second part of binary literal.

**Used SW:**

- MADS 2.1.5, Ubuntu 22.04

**Comment by zbyti** [comment]
> Assembler seems to parse the 0000 as a second argument of mva instead of the second part of binary literal.

as far as I know "nibble separator" in MADS is `_` then `#%1011_1111`

**Comment by mirao** [comment]
A solution would be allowing the `_` separator for binary literals, e.g. `mva #%1100_0000 GPRIOR`

**Comment by tebe6502** [comment]
mva #[% 1 1 0 0  0 0 0 0] GPRIOR

**Comment by mirao** [comment]
@tebe6502 Thank you very much, that's it.
E.g. `mva #[%0010 1010] SDMCTL` works as expected.

**Comment by mirao** [comment]
This case is a bit tricky:
```asm
.by %1010 0011
```
It stores two bytes (instead of one byte originally expected by me) because `.by` allows [a space separator](https://mads-atari8-info.translate.goog/pl/dyrektywy/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en-US#by-byte-bytes-andor-ascii):

1. `$0a`, it's binary `1010`
2. `$0b`, it's decimal `0011`

It can be solved by `[]` too:
```asm
.by [%1010 0011]
```
or by using of `.byte` instead of `.by`
```asm
.byte %1010 0011
```

Both produce the expected byte `$a3`

**Comment by tebe6502** [comment]
Yes, "white spaces" are the equivalent of a comma sign for the .xx: .by, .wo, .he, .sb etc.

default is 'DTA' (dta b( ) is equivalent .BYTE)

dta %1010 0011
dta b(%1010 0011)
dta a(%1010 0011)
